---
- hosts: all
  remote_user: root
  tasks:
  - name: Register and subscribe hosts
    redhat_subscription:
      state: present
      username: 
      password: 
      pool_ids: 8a85f98c635f699f016374de92150d75
