---
- hosts: all
  remote_user: root
  tasks:

  - name: Disable all repos
    command: subscription-manager repos --disable="*"

  - name: Enable OpenShift repos only
    command: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.11-rpms" --enable="rhel-7-server-ansible-2.6-rpms"
