---
- hosts: all
  remote_user: root
  tasks:
  
  - name: install docker
    yum:
      name: docker-1.13.1
      state: present

  - name: copy docker-storage-setup file to remote servers
    copy:
      src: /home/pmamontov/playbooks/docker-storage-setup
      dest: /etc/sysconfig/
  
  - name: configure docker storage
    command: docker-storage-setup

  - name: start and enable docker
    service: name=docker state=started enabled=yes
